name: Lint Code Base

on:
    pull_request:
    push:
      branches:
        - main


jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write


    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper
          # list of changed files within `super-linter`
          fetch-depth: 0


      - name: Lint Code Base
        uses: super-linter/super-linter/slim@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # add the linters to be run
          VALIDATE_TERRAFORM_TFLINT: true
          VALIDATE_YAML: True
          # VALIDATE_DOCKERFILE_HADOLINT: true
          VALIDATE_GITLEAKS: true
          VALIDATE_JAVASCRIPT_ES: true
          VALIDATE_SQL: true
          VALIDATE_GITHUB_ACTIONS: true